# Generated by Django 5.2.3 on 2025-06-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('modelo3d', models.URLField()),
                ('imagen', models.URLField()),
                ('textura_modelo', models.URLField()),
                ('tamaño_alto', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tamaño_ancho', models.DecimalField(decimal_places=1, max_digits=3)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'Hamburguesa',
            },
        ),
    ]
