# Generated by Django 5.2.3 on 2025-06-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburger', '0002_alter_hamburguesa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='imagen',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='modelo3d',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='textura_modelo',
            field=models.URLField(max_length=1000),
        ),
    ]
